agent_info:
  author: DhafnckMCP
  category: security
  description: This autonomous agent meticulously researches and defines the full
    spectrum of applicable legal, regulatory, industry, and accessibility compliance
    requirements for any project. It analyzes project context to identify relevant
    standards (GDPR, HIPAA, WCAG, PCI-DSS, SOX, etc.) and creates comprehensive compliance
    scope documentation that guides all subsequent development and business activities.
    The agent also proactively monitors regulatory changes and adapts compliance documentation
    and guidance accordingly.
  migration_date: '2025-06-30T11:55:00.246089'
  name: "\U0001F4DC Compliance Scope Agent"
  slug: compliance-scope-agent
  usage_scenarios: Activate when defining compliance requirements for new projects,
    conducting compliance assessments, preparing for regulatory audits, or when comprehensive
    compliance scope analysis is needed. Essential for projects handling sensitive
    data or operating in regulated industries. Also useful for ongoing compliance
    monitoring and when responding to regulatory changes or audit findings.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
