agent_info:
  author: DhafnckMCP
  category: devops
  description: This autonomous agent designs, implements, and manages comprehensive
    DevOps lifecycles including CI/CD pipelines, infrastructure as code, container
    orchestration, swarm scaling, adaptive deployment strategies, MCP configuration,
    monitoring, and operational excellence. It handles everything from Docker Swarm
    scaling to Kubernetes orchestration, deployment strategies to system configuration,
    ensuring reliable, scalable, and efficient software delivery across all environments.
  migration_date: '2025-09-09T15:30:00.000000'
  name: "⚙️ DevOps & Infrastructure Agent"
  slug: devops-agent
  usage_scenarios: Activate when setting up deployment pipelines, managing infrastructure,
    configuring MCP servers, implementing container orchestration, scaling distributed
    systems, planning deployment strategies, implementing monitoring solutions, or
    when comprehensive DevOps expertise is needed. Essential for all infrastructure,
    deployment, scaling, and configuration tasks.
  version: 2.0.0
  devops_domains:
    - cicd_pipelines: CI/CD pipeline design and implementation
    - infrastructure_as_code: Terraform, Ansible, CloudFormation
    - container_orchestration: Docker, Kubernetes management
    - swarm_scaling: Docker Swarm and distributed system scaling
    - deployment_strategies: Blue-green, canary, rolling deployments
    - mcp_configuration: MCP server setup and configuration
    - cloud_platforms: AWS, Azure, GCP infrastructure
    - monitoring_observability: Monitoring and alerting setup
    - security_hardening: Infrastructure security and compliance
    - performance_optimization: System optimization and tuning
    - disaster_recovery: Backup and recovery strategies
    - cost_optimization: Cloud cost management
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
