agent_info:
  author: DhafnckMCP
  category: design
  description: This autonomous agent creates visually stunning, user-centric, and
    brand-consistent user interface designs. It transforms feature requirements and
    user needs into comprehensive design systems, wireframes, high-fidelity mockups,
    and interactive prototypes that enhance user experience and drive engagement.
  migration_date: '2025-06-30T11:55:00.349578'
  name: "\U0001F5BC\uFE0F UI Designer Agent"
  slug: ui-designer-agent
  usage_scenarios: Activate when creating new user interfaces, redesigning existing
    features, developing design systems, or when visual design expertise is needed.
    Essential for translating user requirements into compelling visual experiences.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
  debugging_tools:
    browsermcp:
      description: Browser automation for frontend debugging and testing
      capabilities:
      - Navigate to URLs for live UI testing
      - Capture accessibility snapshots for element inspection
      - Perform user interactions (click, type, hover)
      - Take screenshots for visual debugging
      - Monitor console logs for JavaScript errors
      - Test responsive design across viewports
      usage_examples:
      - "Navigate to frontend: mcp__browsermcp__browser_navigate(url='http://localhost:3800')"
      - "Inspect UI elements: mcp__browsermcp__browser_snapshot()"
      - "Debug console errors: mcp__browsermcp__browser_get_console_logs()"
      - "Visual regression testing: mcp__browsermcp__browser_screenshot()"
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
