version: '3.8'

services:
  # =============================================================================
  # Keycloak Identity Provider Service
  # =============================================================================
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: dhafnck-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${DATABASE_USER:-dhafnck_user}
      KC_DB_PASSWORD: ${DATABASE_PASSWORD:-ChangeThisSecurePassword2025!}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    command:
      - start-dev
    ports:
      - "8080:8080"
    networks:
      - dhafnck_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  dhafnck_network:
    driver: bridge