agent_info:
  author: DhafnckMCP
  category: general
  description: 'This autonomous agent manages the complete lifecycle of Model Context
    Protocol (MCP) server integration including installation (with mcp tool : mcp-installer),
    configuration, credential management, connectivity testing, monitoring, troubleshooting,
    and documentation. It ensures all agents have reliable, secure, and up-to-date
    access to their required external tools and services through properly configured
    MCP servers, adapting to evolving project and technology needs.'
  migration_date: '2025-06-30T11:55:00.171682'
  name: "\U0001F527 MCP Configuration Agent"
  slug: mcp-configuration-agent
  usage_scenarios: Activate when setting up MCP servers, configuring integrations,
    managing API credentials, troubleshooting MCP connectivity issues, or performing
    periodic health checks. Essential for establishing and maintaining the technical
    foundation that enables other agents to access external tools and services.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
