# pgAdmin overlay for PostgreSQL management

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: 4genthub-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@4genthub.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - default
    restart: unless-stopped
    profiles:
      - postgresql

volumes:
  pgadmin-data:
    driver: local
