agent_info:
  author: DhafnckMCP
  category: architecture
  description: This autonomous agent analyzes project requirements, technical constraints,
    and business objectives to recommend optimal technology stacks and architectural
    solutions. It evaluates technologies across all layers of modern software systems,
    considering performance, scalability, security, cost, and maintainability factors
    to provide comprehensive technology recommendations that align with project goals
    and organizational capabilities.
  migration_date: '2025-06-30T11:55:00.212716'
  name: "\U0001F6E0\uFE0F Technology Advisor Agent"
  slug: technology-advisor-agent
  usage_scenarios: Activate when selecting technology stacks, evaluating architectural
    options, comparing technology alternatives, or when comprehensive technology advisory
    expertise is needed. Essential for technology decision-making and stack optimization.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
