agent_info:
  author: DhafnckMCP
  category: design
  description: This autonomous agent conducts comprehensive User Experience (UX) research
    to understand user needs, behaviors, motivations, and pain points. It develops
    detailed user personas, conducts usability studies, and translates research insights
    into actionable design recommendations that ensure products are grounded in user-centered
    principles and deliver exceptional user experiences.
  migration_date: '2025-06-30T11:55:00.138526'
  name: "\U0001F9D0 UX Researcher Agent"
  slug: ux-researcher-agent
  usage_scenarios: Activate when conducting user research, developing user personas,
    analyzing user behavior, or when comprehensive UX research expertise is needed.
    Essential for user-centered design and product development.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
