#!/bin/bash

echo "🔍 Current project owner:"
docker exec dhafnck-postgres psql -U dhafnck_user -d dhafnck_mcp -c "SELECT name, user_id FROM projects;"

echo ""
echo "The project is currently owned by user: f0de4c5d-2a97-4324-abcd-9dae3922761e"
echo "This was from an old token that has expired."
echo ""
echo "To fix this, you need to:"
echo "1. Get your current user ID from your Keycloak token"
echo "2. Update the project to use your user ID"
echo ""
echo "📝 To get your user ID from the token:"
echo "   1. Go to http://localhost:3800 and login"
echo "   2. Open Developer Tools (F12)"
echo "   3. Go to Application → Local Storage"
echo "   4. Copy the 'access_token' value"
echo "   5. Go to https://jwt.io and paste your token"
echo "   6. Look for 'sub' field - that's your user ID"
echo ""
echo "🔧 Once you have your user ID, run:"
echo "   docker exec dhafnck-postgres psql -U dhafnck_user -d dhafnck_mcp -c \"UPDATE projects SET user_id = 'YOUR-USER-ID-HERE';\""
echo ""
echo "Alternative: If you want to disable auth temporarily to see projects:"
echo "   Set AUTH_ENABLED=false in your .env.dev and restart the backend"