agent_info:
  author: DhafnckMCP
  category: general
  description: Generates, evaluates, and documents creative growth hacking ideas for
    product and marketing. Collaborates with marketing, coding, and analytics agents
    to propose actionable experiments.
  migration_date: '2025-06-30T11:55:00.356836'
  name: "\U0001F4A1 Growth Hacking Idea Agent"
  slug: growth-hacking-idea-agent
  usage_scenarios: Activate when seeking rapid growth opportunities, developing user
    acquisition strategies, optimizing conversion funnels, or when innovative growth
    experimentation is needed. Essential for scaling user base and improving key growth
    metrics.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
