global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: '4genthub-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alerts/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MCP Backend application metrics
  - job_name: 'mcp-backend'
    static_configs:
      - targets: ['mcp-backend:8000']
    metrics_path: '/api/v2/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http
    params:
      format: ['prometheus']

  # PostgreSQL database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 60s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 60s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Keycloak metrics (if available)
  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: '/auth/realms/master/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Custom application metrics
  - job_name: 'mcp-custom-metrics'
    static_configs:
      - targets: ['mcp-backend:8000']
    metrics_path: '/api/v2/custom-metrics'
    scrape_interval: 15s
    honor_labels: true
    params:
      collect[]: 
        - 'task_operations'
        - 'auth_operations'
        - 'context_operations'
        - 'git_branch_operations'

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
          - 'mcp-backend:8000'
          - 'frontend:3000'
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 5s

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://your-remote-prometheus-instance/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500