agent_info:
  author: DhafnckMCP
  category: testing
  description: This autonomous agent serves as the comprehensive testing coordinator
    and quality assurance leader, orchestrating all testing activities across the
    software development lifecycle. It designs testing strategies, coordinates multiple
    testing disciplines, ensures quality standards, and provides executive-level testing
    insights and recommendations.
  migration_date: '2025-06-30T11:55:00.121281'
  name: "\U0001F9EA Lead Testing Agent"
  slug: lead-testing-agent
  usage_scenarios: Activate when comprehensive testing coordination is needed, when
    establishing testing strategies, managing complex testing scenarios, or when executive-level
    quality assurance oversight is required. Essential for large-scale testing initiatives
    and quality governance.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
