apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    withCredentials: false
    editable: true
    jsonData:
      httpMethod: POST
      keepCookies: []
      timeInterval: "30s"
      queryTimeout: "60s"
      defaultRegion: "default"
      customQueryParameters: ""
      manageAlerts: true
      alertmanagerUid: ""
    secureJsonFields: {}
    version: 1
    readOnly: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    basicAuth: false
    withCredentials: false
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60
      keepCookies: []
    secureJsonFields: {}
    version: 1
    readOnly: false