# Hint System General Configuration
# Controls behavior of the hint analyzer and message display

version: "1.0"
enabled: true

# Display settings
display:
  # Show task status every N tool calls
  task_status_interval: 5

  # Show task warning when no tasks exist for master-orchestrator
  show_no_task_warning: true

  # Maximum hints to show at once
  max_hints_per_tool: 3

  # Display format
  format: "compact"  # compact, verbose, minimal

  # Color coding
  use_colors: false  # Use ASCII markers instead of colors

# Task tracking settings
task_tracking:
  # Enable task tracking in hints
  enabled: true

  # Show task summary format
  summary_format: |
    === TASK STATUS (Tool call #{call_count}) ===
    Active Tasks: {total_tasks}
    In Progress: {in_progress}
    Pending: {pending}
    Blocked: {blocked}
    Current: {current_task}
    =====================================

  # Show detailed task list
  show_detailed_list: false

  # Track task operations
  track_operations: true

  # Warning messages
  warnings:
    no_tasks: |
      [TASK WARNING] No active MCP tasks!
      Master-orchestrator should create task before delegating.

    blocked_tasks: |
      [TASK ALERT] {count} task(s) are BLOCKED and need attention!

    stale_tasks: |
      [TASK INFO] {count} task(s) haven't been updated in over 1 hour.

# Tool call tracking
tool_tracking:
  # Track tool call history
  enabled: true

  # Maximum history to keep
  max_history: 100

  # Pattern detection
  detect_patterns: true

  # Common patterns to detect
  patterns:
    - name: "delegation_without_task"
      sequence: ["Task"]
      without_prior: ["mcp__dhafnck_mcp_http__manage_task"]
      window: 5

    - name: "edit_without_read"
      sequence: ["Edit", "MultiEdit"]
      without_prior: ["Read"]
      window: 3

    - name: "test_without_changelog"
      sequence: ["Write"]
      path_contains: "test"
      without_after: ["Edit"]
      file_contains: "CHANGELOG"
      window: 10

# Session management
session:
  # Session timeout in hours
  timeout_hours: 2

  # Clean up old sessions
  auto_cleanup: true

  # Session data to track
  track_data:
    - tool_calls
    - task_operations
    - file_modifications
    - errors_encountered

# Performance settings
performance:
  # Cache hint evaluations
  cache_hints: true
  cache_ttl_seconds: 60

  # Async processing
  async_evaluation: false

  # Logging
  log_hints: true
  log_file: "hints.log"

# Integration settings
integrations:
  # MCP task tracker
  mcp_task_tracker:
    enabled: true
    auto_track: true

  # File session tracker
  file_session:
    enabled: true
    track_modifications: true

  # Agent state manager
  agent_state:
    enabled: true
    track_agent_changes: true

# Debug settings
debug:
  # Show debug information
  enabled: false

  # Debug output
  show_conditions: false
  show_patterns: false
  show_evaluation: false

  # Save debug logs
  save_logs: false
  log_path: ".claude/hooks/logs/hint_debug.log"