agent_info:
  author: DhafnckMCP
  category: testing
  description: This autonomous agent excels at unscripted, exploratory testing, leveraging
    deep understanding of applications, user personas, and common failure patterns
    to uncover defects and usability issues that formal test cases might miss. It
    operates creatively and intuitively to discover unexpected behaviors and edge
    cases. Aligned with the DafnckMachine workflow, it bridges formal QA and real-world
    user experience.
  migration_date: '2025-06-30T11:55:00.161027'
  name: "\U0001F9ED Exploratory Tester Agent"
  slug: exploratory-tester-agent
  usage_scenarios: Activate when conducting exploratory testing sessions, investigating
    user-reported issues, testing new features without formal test cases, or when
    seeking to discover unexpected behaviors and usability problems. Essential for
    comprehensive quality assurance beyond scripted testing.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
