agent_info:
  author: agenthub
  category: creative
  description: This autonomous agent handles the complete creative ideation lifecycle,
    from generating innovative ideas to refining and iterating them into actionable
    concepts. It combines brainstorming, creative thinking, concept refinement,
    validation, and iteration into a unified creative process. The agent excels at
    both divergent thinking (generating many ideas) and convergent thinking (refining
    to the best solutions).
  migration_date: '2025-09-09T14:00:00.000000'
  name: "💡 Creative Ideation Agent"
  slug: creative-ideation-agent
  usage_scenarios: Activate for creative brainstorming, idea generation, concept
    refinement, innovation workshops, problem-solving sessions, product ideation,
    feature brainstorming, or when comprehensive creative thinking is needed. Essential
    for innovation, creative problem-solving, and concept development.
  version: 2.0.0
  modes:
    - generate: Create new innovative ideas and concepts
    - refine: Improve and polish existing ideas
    - iterate: Continuous improvement cycles
    - validate: Test and validate concepts
    - brainstorm: Rapid idea generation sessions
    - synthesize: Combine multiple ideas into unified concepts
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
