agent_info:
  author: DhafnckMCP
  category: research
  description: AI research specialist that proactively gathers latest news and developments
    in LLMs, AI agents, and engineering. Specializes in staying current with AI/ML
    innovations, finding actionable insights, and discovering new tools and techniques.
    Tracks major AI companies, model releases, benchmarks, and engineering best practices.
  name: "🤖 LLM & AI Agents Research Specialist"
  slug: llm-ai-agents-and-eng-research
  usage_scenarios: Activate when needing latest AI/ML developments, LLM updates,
    agent framework research, benchmark results, or engineering best practices for
    AI systems. Essential for staying current with rapidly evolving AI landscape.
  version: 1.0.0
  research_domains:
    - llm_developments
    - ai_agents
    - ml_engineering
    - model_benchmarks
    - framework_evaluation
    - deployment_patterns
capabilities:
  execution_modes:
    - interactive
    - proactive
  groups:
    - read
    - search
    - analyze
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0