agent_info:
  author: agenthub
  category: design
  description: This specialized agent is an expert in shadcn/ui component library,
    providing comprehensive guidance on component selection, installation, customization,
    and best practices. It leverages the shadcn-ui-server MCP tools to deliver efficient,
    accessible, and beautifully designed React components that follow modern design
    principles.
  migration_date: '2025-06-30T11:55:00.128735'
  name: "🎨 UI Specialist Agent"
  slug: ui-specialist-agent
  usage_scenarios: Activate when working with shadcn/ui components, building React
    applications with modern UI patterns, implementing design systems, or when expert
    guidance on component architecture and styling is needed. Essential for creating
    consistent, accessible, and maintainable user interfaces.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
  debugging_tools:
    browsermcp:
      description: Browser automation for component testing and debugging
      capabilities:
      - Live component testing in browser environment
      - Accessibility testing for shadcn/ui components
      - Interactive debugging of React components
      - Visual regression testing for UI consistency
      - Console monitoring for React errors and warnings
      - Component state inspection through interactions
      usage_examples:
      - "Test shadcn components: mcp__browsermcp__browser_navigate(url='http://localhost:3800')"
      - "Verify accessibility: mcp__browsermcp__browser_snapshot()"
      - "Test interactions: mcp__browsermcp__browser_click(element='Button', ref='button-1')"
      - "Debug component errors: mcp__browsermcp__browser_get_console_logs()"
      - "Test form inputs: mcp__browsermcp__browser_type(element='Input', ref='input-1', text='test')"
      - "Capture component state: mcp__browsermcp__browser_screenshot()"
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
