package utilities

// ORIGIN: transcribed by hand into Go during the port from the Python backend, whose
// fastmcp/utilities/types.py had called the standard library's mimetypes.guess_type. The data is
// CPython 3.14's built-in tables, verified entry for entry rather than asserted: mimeTypesMap is
// exactly CPython 3.14.0's MimeTypes().types_map[True] - the strict table guess_type uses by
// default, 198 entries - and mimeSuffixMap and mimeEncodingsMap are its suffix_map and
// encodings_map. The lookup over them is mimetypes.go.
//
// NO GENERATOR EXISTS, AND NONE EVER DID: nothing in this repository emits this file, and the symbol
// appears in exactly one commit - the port that added it. The tables cannot be re-derived here, so
// this FILE IS HAND-MAINTAINED: edit the maps directly when a content type must change.
//
// DO NOT REGENERATE the data. It is deliberately the BUILT-INS rather than what a runtime reading the
// host's mime files would answer (that map is far larger), so re-deriving it from a host or from a
// different CPython silently changes which content types the server accepts. The "DO NOT EDIT" marker
// was corrected on 2026-10-10, when the marker audit that re-derived models.go's own header found
// this second one (row eeb62d07): an instruction no seat can follow or verify stops future seats from
// doing ordinary work.

var mimeTypesMap = map[string]string{
	".3g2":         "audio/3gpp2",
	".3gp":         "audio/3gpp",
	".3gpp":        "audio/3gpp",
	".3gpp2":       "audio/3gpp2",
	".7z":          "application/x-7z-compressed",
	".a":           "application/octet-stream",
	".aac":         "audio/aac",
	".adts":        "audio/aac",
	".ai":          "application/postscript",
	".aif":         "audio/x-aiff",
	".aifc":        "audio/x-aiff",
	".aiff":        "audio/x-aiff",
	".ass":         "audio/aac",
	".au":          "audio/basic",
	".avi":         "video/vnd.avi",
	".avif":        "image/avif",
	".bat":         "text/plain",
	".bcpio":       "application/x-bcpio",
	".bin":         "application/octet-stream",
	".bmp":         "image/bmp",
	".c":           "text/plain",
	".cdf":         "application/x-netcdf",
	".cpio":        "application/x-cpio",
	".csh":         "application/x-csh",
	".css":         "text/css",
	".csv":         "text/csv",
	".deb":         "application/x-debian-package",
	".dll":         "application/octet-stream",
	".doc":         "application/msword",
	".docx":        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".dot":         "application/msword",
	".dvi":         "application/x-dvi",
	".emf":         "image/emf",
	".eml":         "message/rfc822",
	".eot":         "application/vnd.ms-fontobject",
	".eps":         "application/postscript",
	".epub":        "application/epub+zip",
	".etx":         "text/x-setext",
	".exe":         "application/octet-stream",
	".fits":        "image/fits",
	".flac":        "audio/flac",
	".g3":          "image/g3fax",
	".gif":         "image/gif",
	".glb":         "model/gltf-binary",
	".gltf":        "model/gltf+json",
	".gtar":        "application/x-gtar",
	".gz":          "application/gzip",
	".h":           "text/plain",
	".h5":          "application/x-hdf5",
	".hdf":         "application/x-hdf",
	".heic":        "image/heic",
	".heif":        "image/heif",
	".htm":         "text/html",
	".html":        "text/html",
	".ico":         "image/vnd.microsoft.icon",
	".ief":         "image/ief",
	".jp2":         "image/jp2",
	".jpe":         "image/jpeg",
	".jpeg":        "image/jpeg",
	".jpg":         "image/jpeg",
	".jpm":         "image/jpm",
	".jpx":         "image/jpx",
	".js":          "text/javascript",
	".json":        "application/json",
	".ksh":         "text/plain",
	".latex":       "application/x-latex",
	".loas":        "audio/aac",
	".m1v":         "video/mpeg",
	".m3u":         "application/vnd.apple.mpegurl",
	".m3u8":        "application/vnd.apple.mpegurl",
	".m4a":         "audio/mp4",
	".m4v":         "video/x-m4v",
	".man":         "application/x-troff-man",
	".markdown":    "text/markdown",
	".md":          "text/markdown",
	".me":          "application/x-troff-me",
	".mht":         "message/rfc822",
	".mhtml":       "message/rfc822",
	".mif":         "application/x-mif",
	".mjs":         "text/javascript",
	".mk3d":        "video/matroska-3d",
	".mka":         "audio/matroska",
	".mkv":         "video/matroska",
	".mov":         "video/quicktime",
	".movie":       "video/x-sgi-movie",
	".mp2":         "audio/mpeg",
	".mp3":         "audio/mpeg",
	".mp4":         "video/mp4",
	".mpa":         "video/mpeg",
	".mpe":         "video/mpeg",
	".mpeg":        "video/mpeg",
	".mpg":         "video/mpeg",
	".ms":          "application/x-troff-ms",
	".n3":          "text/n3",
	".nc":          "application/x-netcdf",
	".nq":          "application/n-quads",
	".nt":          "application/n-triples",
	".nws":         "message/rfc822",
	".o":           "application/octet-stream",
	".obj":         "application/octet-stream",
	".oda":         "application/oda",
	".odg":         "application/vnd.oasis.opendocument.graphics",
	".odp":         "application/vnd.oasis.opendocument.presentation",
	".ods":         "application/vnd.oasis.opendocument.spreadsheet",
	".odt":         "application/vnd.oasis.opendocument.text",
	".ogg":         "audio/ogg",
	".ogv":         "video/ogg",
	".ogx":         "application/ogg",
	".opus":        "audio/opus",
	".otf":         "font/otf",
	".p12":         "application/x-pkcs12",
	".p7c":         "application/pkcs7-mime",
	".pbm":         "image/x-portable-bitmap",
	".pdf":         "application/pdf",
	".pfx":         "application/x-pkcs12",
	".pgm":         "image/x-portable-graymap",
	".php":         "application/x-httpd-php",
	".pl":          "text/plain",
	".png":         "image/png",
	".pnm":         "image/x-portable-anymap",
	".pot":         "application/vnd.ms-powerpoint",
	".ppa":         "application/vnd.ms-powerpoint",
	".ppm":         "image/x-portable-pixmap",
	".pps":         "application/vnd.ms-powerpoint",
	".ppt":         "application/vnd.ms-powerpoint",
	".pptx":        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	".ps":          "application/postscript",
	".pwz":         "application/vnd.ms-powerpoint",
	".py":          "text/x-python",
	".pyc":         "application/x-python-code",
	".pyo":         "application/x-python-code",
	".qt":          "video/quicktime",
	".ra":          "audio/x-pn-realaudio",
	".ram":         "application/x-pn-realaudio",
	".rar":         "application/vnd.rar",
	".ras":         "image/x-cmu-raster",
	".rdf":         "application/xml",
	".rgb":         "image/x-rgb",
	".roff":        "application/x-troff",
	".rpm":         "application/x-rpm",
	".rst":         "text/x-rst",
	".rtf":         "text/rtf",
	".rtx":         "text/richtext",
	".sgm":         "text/x-sgml",
	".sgml":        "text/x-sgml",
	".sh":          "application/x-sh",
	".shar":        "application/x-shar",
	".snd":         "audio/basic",
	".so":          "application/octet-stream",
	".src":         "application/x-wais-source",
	".srt":         "text/plain",
	".stl":         "model/stl",
	".sv4cpio":     "application/x-sv4cpio",
	".sv4crc":      "application/x-sv4crc",
	".svg":         "image/svg+xml",
	".swf":         "application/x-shockwave-flash",
	".t":           "application/x-troff",
	".t38":         "image/t38",
	".tar":         "application/x-tar",
	".tcl":         "application/x-tcl",
	".tex":         "application/x-tex",
	".texi":        "application/x-texinfo",
	".texinfo":     "application/x-texinfo",
	".tfx":         "image/tiff-fx",
	".tif":         "image/tiff",
	".tiff":        "image/tiff",
	".tr":          "application/x-troff",
	".trig":        "application/trig",
	".tsv":         "text/tab-separated-values",
	".ttf":         "font/ttf",
	".txt":         "text/plain",
	".ustar":       "application/x-ustar",
	".vcf":         "text/x-vcard",
	".vtt":         "text/vtt",
	".wasm":        "application/wasm",
	".wav":         "audio/vnd.wave",
	".weba":        "audio/webm",
	".webm":        "video/webm",
	".webmanifest": "application/manifest+json",
	".webp":        "image/webp",
	".wiz":         "application/msword",
	".wmf":         "image/wmf",
	".wmv":         "video/x-ms-wmv",
	".woff":        "font/woff",
	".woff2":       "font/woff2",
	".wsdl":        "application/xml",
	".xbm":         "image/x-xbitmap",
	".xlb":         "application/vnd.ms-excel",
	".xls":         "application/vnd.ms-excel",
	".xlsx":        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".xml":         "text/xml",
	".xpdl":        "application/xml",
	".xpm":         "image/x-xpixmap",
	".xsl":         "application/xml",
	".xwd":         "image/x-xwindowdump",
	".yaml":        "application/yaml",
	".yml":         "application/yaml",
	".zip":         "application/zip",
}

var mimeSuffixMap = map[string]string{
	".svgz": ".svg.gz",
	".taz":  ".tar.gz",
	".tbz2": ".tar.bz2",
	".tgz":  ".tar.gz",
	".txz":  ".tar.xz",
	".tz":   ".tar.gz",
}

var mimeEncodingsMap = map[string]string{
	".Z":   "compress",
	".br":  "br",
	".bz2": "bzip2",
	".gz":  "gzip",
	".xz":  "xz",
}
