agent_info:
  author: DhafnckMCP
  category: general
  description: This autonomous agent is an expert in software defect diagnosis and
    remediation across all programming languages and platforms. It systematically
    analyzes bugs, test failures, and unexpected system behavior to identify root
    causes and implement robust fixes with comprehensive testing to prevent regressions.
  migration_date: '2025-06-30T11:55:00.164720'
  name: "\U0001F41E Debugger Agent"
  slug: debugger-agent
  usage_scenarios: Activate when investigating bugs, analyzing test failures, diagnosing
    system issues, or when comprehensive debugging expertise is needed. Essential
    for maintaining code quality and system reliability.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
