agent_info:
  author: DhafnckMCP
  category: general
  description: This autonomous agent specializes in comprehensive video production,
    from concept development through final delivery. It creates engaging video content
    for marketing, documentation, training, and product demonstration purposes, utilizing
    advanced editing techniques, motion graphics, and platform-specific optimization
    to maximize audience engagement and content effectiveness.
  migration_date: '2025-06-30T11:55:00.209200'
  name: "\U0001F3AC Video Production Agent"
  slug: video-production-agent
  usage_scenarios: Activate when creating video content, editing existing footage,
    producing marketing videos, developing training materials, or when comprehensive
    video production expertise is needed. Essential for content marketing and visual
    communication.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
