services:
  dhafnck-mcp:
    build:
      context: ../..
      dockerfile: dhafnck_mcp_main/docker/Dockerfile
      target: runtime
    image: dhafnck/mcp-server:latest
    container_name: dhafnck-mcp-server
    restart: unless-stopped
    
    # Port mapping for HTTP MCP server
    ports:
      - "8000:8000"
    
    # Default command (stdio mode for MCP)
    # command: ["python", "-m", "fastmcp.server.mcp_entry_point"]
    
    # Environment variables
    environment:
      PYTHONPATH: /app/src
      DHAFNCK_DATA_PATH: /data
      FASTMCP_LOG_LEVEL: INFO
      FASTMCP_ENABLE_RICH_TRACEBACKS: 0
      DATA_STORAGE_MODE: internal
      MCP_DB_PATH: /data/dhafnck_mcp.db
      TASKS_JSON_PATH: /data/tasks
      PROJECTS_FILE_PATH: /data/projects/projects.json
      CURSOR_RULES_DIR: /data/rules
      AGENT_LIBRARY_DIR_PATH: /app/agent-library
      DHAFNCK_AUTH_ENABLED: false
      DHAFNCK_MVP_MODE: true
      SUPABASE_URL: ""
      SUPABASE_ANON_KEY: ""
      DHAFNCK_TOKEN: ""
      FASTMCP_TRANSPORT: streamable-http
      FASTMCP_HOST: 0.0.0.0
      FASTMCP_PORT: 8000
      REDIS_URL: redis://redis:6379/0
      SESSION_TTL: 3600
      MAX_EVENTS_PER_SESSION: 1000
      SESSION_COMPRESSION: true
      SESSION_KEY_PREFIX: "mcp:session:"
      REDIS_SOCKET_TIMEOUT: 5
      REDIS_CONNECT_TIMEOUT: 5
      REDIS_HEALTH_CHECK_INTERVAL: 30
      SESSION_PERSISTENCE_ENABLED: true
      FALLBACK_TO_MEMORY: true
      SESSION_DEBUG_LOGGING: false
    
    # Volume mounts for data persistence
    volumes:
      # Data persistence
      - dhafnck_data:/data
      - dhafnck_logs:/app/logs
      
      # Configuration files (optional - for advanced users)
      - ./config:/app/config:ro
      
      # Development mode: mount source code (comment out for production)
      - ../src:/app/src:ro  # Mount source code for development
    
    # Health check for HTTP mode (check health endpoint)
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # User specification (matches Dockerfile)
    # user: "1000:1000"  # Disabled for permission fix
    
    # Network mode for MCP (typically stdio, but HTTP available)
    # network_mode: "bridge"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: dhafnck-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
        reservations:
          memory: 128M
          cpus: '0.1'

  dhafnck-frontend:
    build:
      context: ../../dhafnck-frontend
      dockerfile: docker/Dockerfile
    image: dhafnck/frontend:latest
    container_name: dhafnck-frontend
    restart: unless-stopped
    ports:
      - "3800:80"
    depends_on:
      - dhafnck-mcp
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'

# Named volumes for data persistence
volumes:
  dhafnck_data:
    driver: local
  
  dhafnck_logs:
    driver: local
  
  redis_data:
    driver: local 