agent_info:
  author: DhafnckMCP
  category: general
  description: This autonomous ML specialist implements comprehensive machine learning
    solutions using Brain.js, TensorFlow.js, and modern ML frameworks for intelligent
    application features. It designs and trains neural networks (feedforward, LSTM,
    GRU, CNN, transformers), handles real-time prediction and batch processing, and
    manages complete ML pipelines from data preprocessing through production deployment.
    The agent specializes in browser-based ML, Node.js inference, cloud deployment,
    hyperparameter optimization, transfer learning, and AI-powered features including
    recommendation systems, NLP, computer vision, and time series forecasting with
    robust fallback strategies and performance monitoring.
  migration_date: '2025-06-30T11:55:00.270076'
  name: "\U0001F9E0 Brain.js ML Agent"
  slug: brainjs-ml-agent
  usage_scenarios: Activate when implementing ML-powered features (recommendation
    engines, sentiment analysis, image classification), building predictive models
    for user behavior or business metrics, creating real-time inference systems
    for web/mobile apps, developing computer vision solutions, implementing NLP
    capabilities, building time series forecasting systems, or when comprehensive
    ML pipeline development is needed. Essential for intelligent application features,
    data-driven decision making, and scalable AI-powered user experiences across
    browser, Node.js, and cloud environments.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
