#!/usr/bin/env python3
"""Per-seat permission policy for omp seats, written as each seat's own config.

OpenRig launches an omp seat in exactly one of two postures: ``yolo`` (every tool
call is approved) or ``always-ask``, which the managed runner auto-cancels, so that
seat can call no tool at all. Nothing in between exists on the OpenRig side
(``rig seat set-permissions`` refuses omp). So every seat runs ``yolo`` and the
restrictions live where omp enforces them: ``<seat state>/agent/config.yml``.

omp honours two controls in every approval mode, and both are used here:

* ``bash.patterns`` - ordered shell-command rules. ``allowCompoundCommands`` makes it
  evaluate each command of ``a && b`` and ``a; b`` on its own, so an anchored pattern
  such as ``git push*`` also catches ``cd x && git push``.
* ``tools.approval`` - a per-tool ``deny``, including the MCP tools (``mcp__<server>_<tool>``).

``mcp.startupTimeoutMs: 0`` is written too. omp waits 250 ms by default for MCP tools at
startup; the HTTPS agenthub server is slower than that, so without it a seat's first turns
run without the 4genthub tools.

THIS IS A GUARD RAIL AGAINST ACCIDENTS, NOT A SANDBOX. A seat that can write files or run
``eval`` can still do anything these rules block by another route. The rules encode what
the project already forbids in prose: only the principal pushes, nobody amends or
force-resets the shared tree, no seat touches production or kills the tmux server, and
rig lifecycle is the lead's.

Usage::

    openrig_seat_policy.py show SEAT --rig RIG        print one seat's config
    openrig_seat_policy.py apply --rig RIG [--check]  write every seat's config.yml; with
                                                      --check write nothing and exit 1 on drift
    openrig_seat_policy.py notice --rig RIG [--check] write every seat's AGENTS.md (its limits in
                                                      plain words, loaded by omp into the session)

A running seat reads its config at start, so ``apply`` takes effect on the next launch.
"""

import argparse
import json
import sys
from pathlib import Path

EXIT_OK = 0
EXIT_DRIFT = 1
EXIT_USAGE = 2

DEFAULT_STATE_ROOT = Path.home() / ".openrig" / "state" / "omp"

# rig -> seat -> role. An unlisted rig or seat is an error: there is no permissive default.
SEAT_ROLES = {
    "4genthub-min": {
        "lead": "lead",
        "go-dev": "dev",
        "go-dev2": "dev",
        "fe-dev": "dev",
        "web-dev": "dev",
        "skills-dev": "dev",
        "context-dev": "dev",
        "feedback-dev": "dev",
        "reviewer": "reviewer",
        "writer": "writer",
    },
}

# Denied for every seat. Anchored: the compound-command evaluation matches each command.
COMMON_BASH_DENY = [
    "git push*",
    "git reset --hard*",
    "git clean*",
    "git checkout -- *",
    "git stash drop*",
    "git stash clear*",
    "git commit*--amend*",
    "git add -A*",
    "git add --all*",
    "git add .",
    "rm -rf*",
    "rm -fr*",
    "sudo *",
    "ssh *",
    "scp *",
    "docker *",
    "tmux kill-*",
    "pkill *",
    "killall *",
    "printenv*",
    "cat *deepseek/env*",
    "rig down*",
    "rig up*",
    "rig remove*",
]

# Rig lifecycle belongs to the lead, who restarts seats; the other roles only message and read.
NON_LEAD_BASH_DENY = [
    "rig launch*",
    "rig seat stop*",
    "rig seat launch*",
    "rig seat clean*",
    "rig seat set-*",
]

# The 4genthub MCP tools that manage agents, seats and the server itself are the lead's. The
# task, subtask, context, project and branch tools - the context sync - stay open to everyone.
NON_LEAD_TOOL_DENY = [
    "mcp__agenthub_http_manage_agent",
    "mcp__agenthub_http_manage_connection",
    "mcp__agenthub_http_manage_seat",
]

# A reviewer reads and reports; it does not rewrite source (it can still write its verdict files).
REVIEWER_TOOL_DENY = ["edit", "ast_edit"]


def policy_for(role: str) -> tuple[list[str], list[str]]:
    """Return (bash patterns to deny, tools to deny) for a role."""
    bash = list(COMMON_BASH_DENY)
    tools: list[str] = []
    if role != "lead":
        bash += NON_LEAD_BASH_DENY
        tools += NON_LEAD_TOOL_DENY
    if role == "reviewer":
        tools += REVIEWER_TOOL_DENY
    return bash, tools


def render_config(seat: str, role: str) -> str:
    """The seat's config.yml. json.dumps gives YAML-safe double-quoted scalars."""
    bash, tools = policy_for(role)
    lines = [
        f"# generated by scripts/openrig_seat_policy.py for {seat} (role: {role}) - do not edit",
        "mcp:",
        "  startupTimeoutMs: 0",
        "bash:",
        "  allowCompoundCommands: true",
        "  patterns:",
    ]
    for pattern in bash:
        lines += [f"    - match: {json.dumps(pattern)}", "      approval: deny"]
    if tools:
        lines += ["tools:", "  approval:"]
        lines += [f"    {tool}: deny" for tool in tools]
    return "\n".join(lines) + "\n"


def render_notice(seat: str, role: str) -> str:
    """The seat's AGENTS.md: its own limits in plain words, from the same tables as the config.

    omp loads ``<agent dir>/AGENTS.md`` into every session, so the seat learns the limits before it
    runs into one. The text says what is refused, why, and what to do instead; it asks the seat not
    to route around a refusal, because the rules are a guard rail and cannot stop a determined one.
    """
    bash, tools = policy_for(role)
    lines = [
        f"<!-- generated by scripts/openrig_seat_policy.py for {seat} (role: {role}) - do not edit -->",
        f"# Your limits as seat `{seat}` (role: {role})",
        "",
        "Your tool calls are checked against a policy. A refused call returns `Tool ... is blocked by tool policy`.",
        "That is a rule, not a fault. **Do not retry it, rephrase it, or reach the same effect another way**",
        "(a script, `eval`, a file write). Do the allowed alternative below, or ask the lead.",
        "",
        "## Refused shell commands (matched at the start of each command, also inside `a && b`)",
        "",
    ]
    lines += [f"- `{pattern}`" for pattern in bash]
    lines += [
        "",
        "Instead:",
        "",
        "- **Push**: you never push. Commit, then tell the lead the hash; the principal pushes.",
        "- **Commit**: stage explicit paths (`git add -- <path>`) and commit with `git commit -m ... -- <path>`. The tree is shared with other seats, so never `git add .`, `-A` or `--amend`, and never reset, clean or discard.",
        "- **Delete**: remove one named file at a time; never a recursive forced delete.",
        "- **Stop, restart or remove seats or the rig**: "
        + ("the principal does that; ask it." if role == "lead" else "ask the lead."),
        "- **Secrets and environment**: the deepseek and agenthub tokens are not yours to print or read.",
    ]
    if tools:
        lines += ["", "## Refused tools", ""]
        lines += [f"- `{tool}`" for tool in tools]
        lines += [""]
        if role != "lead":
            lines += [
                "The 4genthub tools for tasks, subtasks, context, projects and branches (`manage_task`, `manage_subtask`, `manage_context`, `manage_project`, `manage_git_branch`) and `call_seat` are open to you. Agent, seat and connection management belong to the lead.",
            ]
        if role == "reviewer":
            lines += [
                "You read and report. `edit` and `ast_edit` are refused; write your verdict to a file instead.",
            ]
    lines += [
        "",
        "## Always open to you",
        "",
        "Reading any file, running tests and builds, `deepseek_agent` for offloaded work, and the 4genthub tools above. Call them with `write` to `xd://mcp__<server>_<tool>`.",
    ]
    return "\n".join(lines) + "\n"


def seat_roles(rig: str) -> dict[str, str]:
    if rig not in SEAT_ROLES:
        raise SystemExit(f"no policy table for rig {rig!r}; add it to SEAT_ROLES")
    return SEAT_ROLES[rig]


def config_path(state_root: Path, rig: str, seat: str) -> Path:
    return state_root / f"{rig}-{seat}@{rig}" / "agent" / "config.yml"


def notice_path(state_root: Path, rig: str, seat: str) -> Path:
    return config_path(state_root, rig, seat).with_name("AGENTS.md")


def cmd_notice(args: argparse.Namespace) -> int:
    """Write every seat's AGENTS.md; with --check write nothing and exit 1 on drift."""
    state_root = Path(args.state_root)
    drift = 0
    for seat, role in seat_roles(args.rig).items():
        path = notice_path(state_root, args.rig, seat)
        if not path.parent.is_dir():
            print(
                f"{seat}: no agent directory at {path.parent} (never launched?)",
                file=sys.stderr,
            )
            return EXIT_USAGE
        want = render_notice(seat, role)
        if path.exists() and path.read_text() == want:
            print(f"{seat}: ok ({role})")
            continue
        drift += 1
        if args.check:
            print(f"{seat}: DRIFT ({role})")
            continue
        path.write_text(want)
        print(f"{seat}: written ({role})")
    return EXIT_DRIFT if args.check and drift else EXIT_OK


def cmd_show(args: argparse.Namespace) -> int:
    roles = seat_roles(args.rig)
    if args.seat not in roles:
        print(f"seat {args.seat!r} has no role in rig {args.rig!r}", file=sys.stderr)
        return EXIT_USAGE
    sys.stdout.write(render_config(args.seat, roles[args.seat]))
    return EXIT_OK


def policy_keys_match(want: str, have: str | None) -> bool:
    """Whether ``have`` carries the policy's own keys exactly as ``want`` states them.

    STRUCTURAL RATHER THAN BYTE-EQUAL, and the reason is that the pipeline now writes this file too:
    ``openrig_seat_sync.py rig`` applies this document to the seat's ``config.yml`` and MERGES it,
    keeping whatever else the runtime's file carries, so a byte comparison would call a
    correctly-policed seat drifty. What must hold is exact: every key this module defines, at the
    value it defines. Keys it does not define are none of its business.
    """
    if have is None:
        return False
    try:
        import yaml
    except ImportError as err:  # pragma: no cover - environment dependent
        raise SystemExit(f"PyYAML is required to check a seat's config: {err}") from err
    try:
        wanted = yaml.safe_load(want)
        present = yaml.safe_load(have) or {}
    except yaml.YAMLError:
        return False
    if not isinstance(wanted, dict):
        return False
    if not isinstance(present, dict):
        return False
    return all(present.get(key) == value for key, value in wanted.items())


def cmd_apply(args: argparse.Namespace) -> int:
    state_root = Path(args.state_root)
    drift = 0
    for seat, role in seat_roles(args.rig).items():
        path = config_path(state_root, args.rig, seat)
        if not path.parent.is_dir():
            print(
                f"{seat}: no agent directory at {path.parent} (never launched?)",
                file=sys.stderr,
            )
            return EXIT_USAGE
        want = render_config(seat, role)
        have = path.read_text() if path.exists() else None
        if policy_keys_match(want, have):
            print(f"{seat}: ok ({role})")
            continue
        drift += 1
        if args.check:
            print(f"{seat}: DRIFT ({role})")
            continue
        path.write_text(want)
        print(f"{seat}: written ({role})")
    return EXIT_DRIFT if args.check and drift else EXIT_OK


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    show = sub.add_parser("show", help="print one seat's config")
    show.add_argument("seat")
    show.add_argument("--rig", required=True)
    show.set_defaults(func=cmd_show)
    apply = sub.add_parser("apply", help="write every seat's config.yml")
    apply.add_argument("--rig", required=True)
    apply.add_argument("--state-root", default=str(DEFAULT_STATE_ROOT))
    apply.add_argument(
        "--check", action="store_true", help="write nothing; exit 1 on drift"
    )
    apply.set_defaults(func=cmd_apply)
    notice = sub.add_parser(
        "notice", help="write every seat's AGENTS.md, its limits in plain words"
    )
    notice.add_argument("--rig", required=True)
    notice.add_argument("--state-root", default=str(DEFAULT_STATE_ROOT))
    notice.add_argument(
        "--check", action="store_true", help="write nothing; exit 1 on drift"
    )
    notice.set_defaults(func=cmd_notice)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
