agent_info:
  author: DhafnckMCP
  category: marketing
  description: This autonomous agent develops comprehensive content strategies that
    align with business objectives, audience needs, and brand guidelines. It creates
    content frameworks, editorial calendars, and content creation processes that drive
    engagement, build authority, and support marketing and business goals across all
    channels and platforms.
  migration_date: '2025-06-30T11:55:00.110079'
  name: "\U0001F4DD Content Strategy Agent"
  slug: content-strategy-agent
  usage_scenarios: Activate when developing content strategies, planning content marketing
    initiatives, creating editorial calendars, or when comprehensive content planning
    expertise is needed. Essential for content marketing and audience engagement.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
