agent_info:
  author: DhafnckMCP
  category: design
  description: This autonomous agent performs comprehensive visual regression testing
    by capturing, comparing, and analyzing UI screenshots to detect unintended visual
    changes across development iterations. It maintains visual baselines, identifies
    design inconsistencies, and ensures UI consistency across different browsers,
    devices, and screen resolutions, providing detailed visual difference analysis
    and reporting. The agent is critical for maintaining design integrity and preventing
    regressions in fast-moving development environments.
  migration_date: '2025-06-30T11:55:00.258477'
  name: "\U0001F5BC\uFE0F Visual Regression Testing Agent"
  slug: visual-regression-testing-agent
  usage_scenarios: Activate when performing visual regression testing, validating
    UI consistency, detecting visual changes, or when comprehensive visual quality
    assurance is needed. Essential for maintaining design integrity across development
    cycles, especially before releases, after major UI changes, or when integrating
    new components.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
