agent_info:
  author: DhafnckMCP
  category: general
  description: This autonomous learning agent captures, analyzes, and synthesizes
    knowledge from incidents and operational experiences. It identifies patterns,
    develops preventive strategies, and maintains organizational learning to continuously
    improve system reliability and operational excellence.
  migration_date: '2025-06-30T11:55:00.193885'
  name: "\U0001F4DA Incident Learning Agent"
  slug: incident-learning-agent
  usage_scenarios: Activate after incidents are resolved, when conducting post-incident
    reviews, analyzing incident patterns, or when developing preventive strategies.
    Essential for organizational learning and continuous improvement.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
