# Docker Compose for Supabase Cloud Database
# This configuration uses Supabase cloud database instead of local PostgreSQL

services:
  # Redis for caching (still local)
  redis:
    image: redis:7-alpine
    container_name: dhafnck-redis
    command: >
      redis-server
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
      --tcp-backlog 128
      --tcp-keepalive 60
      --timeout 300
      --databases 2
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - dhafnck-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
        reservations:
          cpus: '0.05'
          memory: 64M
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # Backend connected to Supabase
  backend:
    build:
      context: ../..
      dockerfile: dhafnck_mcp_main/docker/Dockerfile.optimized
      args:
        - ENV=${ENV:-production}
      cache_from:
        - dhafnck-backend:cache
    container_name: dhafnck-backend
    environment:
      # Supabase Database Configuration
      - DATABASE_TYPE=${DATABASE_TYPE:-supabase}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}
      - SUPABASE_REGION=${SUPABASE_REGION}
      # Redis Configuration
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # Security Configuration
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
      # Application Configuration
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-INFO}
      - CORS_ORIGINS=${CORS_ORIGINS}
      # FastMCP Configuration
      - FASTMCP_TRANSPORT=streamable-http
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8000
      # Performance tuning
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONOPTIMIZE=2
      - WEB_CONCURRENCY=2
      - MAX_WORKERS=2
    volumes:
      - backend-data:/app/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 50M
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - dhafnck-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend
  frontend:
    build:
      context: ../..
      dockerfile: docker-system/docker/frontend.optimized.Dockerfile
      args:
        - NODE_ENV=production
      cache_from:
        - dhafnck-frontend:cache
    container_name: dhafnck-frontend
    environment:
      - VITE_API_URL=${BACKEND_URL:-http://localhost:8000}
      - VITE_WS_URL=${WS_URL:-ws://localhost:8000}
      - NODE_ENV=production
      # Supabase configuration for frontend
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
    volumes:
      - frontend-static:/usr/share/nginx/html:ro
      - type: tmpfs
        target: /var/cache/nginx
        tmpfs:
          size: 10M
      - type: tmpfs
        target: /var/run
        tmpfs:
          size: 5M
    ports:
      - "${FRONTEND_PORT:-3800}:80"
    depends_on:
      - backend
    networks:
      - dhafnck-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/"]
      interval: 60s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  redis-data:
    name: dhafnck-redis-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/redis
  backend-data:
    name: dhafnck-backend-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/backend
  frontend-static:
    name: dhafnck-frontend-static
    driver: local

networks:
  dhafnck-network:
    name: dhafnck-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dhafnck0
    ipam:
      config:
        - subnet: 172.28.0.0/16