# Development overrides
services:
  postgres:
    ports:
      - "5432:5432"  # Expose for local development tools
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
    volumes:
      - ./postgres-dev-config.conf:/etc/postgresql/postgresql.conf:ro

  redis:
    ports:
      - "6379:6379"  # Expose for local development tools

  backend:
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - WATCHDOG_ENABLE=true  # Enable hot reload
      - FASTMCP_TRANSPORT=streamable-http
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8000
    volumes:
      # Mount source code for hot reload
      - ../../dhafnck_mcp_main/src:/app/src:cached
      - ../../dhafnck_mcp_main/tests:/app/tests:cached
      - ../../dhafnck_mcp_main/scripts:/app/scripts:cached
      # Mount local data directory
      - ../../dhafnck_mcp_main/data:/app/data
    command: ["python", "-m", "fastmcp", "--transport", "streamable-http"]

  frontend:
    build:
      context: ../..
      dockerfile: docker-system/docker/frontend.dev.Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    volumes:
      # Mount source code for hot reload
      - ../../dhafnck-frontend/src:/app/src:cached
      - ../../dhafnck-frontend/public:/app/public:cached
      # Exclude node_modules
      - /app/node_modules
    command: npm start
    ports:
      - "3000:3000"  # Vite dev server port

  # Development-only services
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dhafnck-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dhafnck.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - dhafnck-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    profiles:
      - tools

  mailhog:
    image: mailhog/mailhog:latest
    container_name: dhafnck-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - dhafnck-network
    profiles:
      - tools

volumes:
  pgadmin-data:
    name: dhafnck-pgadmin-data