services:
  dhafnck-backend:
    build:
      context: ../..
      dockerfile: dhafnck_mcp_main/docker/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: dhafnck-backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@dhafnck-postgres:5432/dhafnck_mcp
      - DATABASE_TYPE=postgresql
      - REDIS_URL=redis://dhafnck-redis:6379
      - REDIS_PASSWORD=dev_redis_password_123
      - FASTMCP_TRANSPORT=streamable-http
      - FASTMCP_PORT=8000
    depends_on:
      - dhafnck-postgres
      - dhafnck-redis
    networks:
      - dhafnck-network
    restart: unless-stopped

  dhafnck-frontend:
    build:
      context: ../..
      dockerfile: dhafnck-frontend/docker/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    container_name: dhafnck-frontend
    ports:
      - "3800:80"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - dhafnck-backend
    networks:
      - dhafnck-network
    restart: unless-stopped

  dhafnck-postgres:
    image: postgres:15-alpine
    container_name: dhafnck-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dhafnck_mcp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dhafnck-postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - dhafnck-network
    restart: unless-stopped

  dhafnck-redis:
    image: redis:7-alpine
    container_name: dhafnck-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass dev_redis_password_123
    volumes:
      - dhafnck-redis-data:/data
    networks:
      - dhafnck-network
    restart: unless-stopped

volumes:
  dhafnck-postgres-data:
  dhafnck-redis-data:

networks:
  dhafnck-network:
    driver: bridge