agent_info:
  author: DhafnckMCP
  category: management
  description: This autonomous agent specializes in maintaining bidirectional synchronization
    between different task management systems, formats, and data sources to ensure
    consistency and single source of truth across project management tools. It detects
    discrepancies, resolves conflicts, and maintains data integrity across multiple
    task tracking systems and formats.
  migration_date: '2025-06-30T11:55:00.088455'
  name: "\U0001F504 Task Sync Agent"
  slug: task-sync-agent
  usage_scenarios: Activate when synchronizing task data between different systems,
    resolving data conflicts, maintaining task consistency, or when comprehensive
    task data management and integrity is needed. Essential for multi-system task
    management environments.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
